on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: DISABLE_ESLINT_PLUGIN=true npm run build


    - name: Deploy via SCP to DigitalOcean (CloudPanel)
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "build/*"
        target: "/home/pluxestudio/htdocs/pluxestudio.com/"  # <-- change this path to your actual web root
        strip_components: 1

    - name: (Optional) Restart Web Server or App
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "React app deployed at /home/pluxestudio/htdocs/pluxestudio.com/"
